# intervals: [1m, 2m, 5m, 15m, 30m] #1m, 2m, 5m, 15m, 30m, 60m, 90m, 1h, 4h, 1d, 5d, 1wk, 1mo, 3mo
tz: Asia/Kolkata
cron_schedules:
  # "1m": { "minute": "*/1", "hour": 9-16, "second": "0" } # runs at 0 seconds of every minute
  # "2m": { "minute": "*/2", "hour": 9-16, "second": "5" } # runs at 5 seconds of every 2nd minute
  "5m": { "minute": "*/5", "hour": 9-16, "second": "10" } # runs at 10 seconds of every 5th minute
  "15m": { "minute": "*/15", "hour": 9-16, "second": "15" } # runs at 15 seconds of every 15th minute
  "30m": { "minute": "*/30", "hour": 9-16, "second": "20" } # runs at 20 seconds of every 30th minute
  "1h": { "minute": "0", "hour": "9-16", "second": "25" } # runs at 25 seconds of the 0th minute each hour
  "1d": { "hour": 16, "minute": 6, "second": "30" } # runs at 16:06:30
  "1wk": { "hour": 16, "minute": 7, "second": "35" } # runs on Friday at 16:07
  "notification": { "minute": "*/7" } # runs every 7th minute
indicators:
  sma:
    periods: [5, 10, 20, 50, 100, 200]
    sources: ["Open", "High", "Low", "Close"]
  ema:
    periods: [5, 10, 20, 50, 100, 200]
    sources: ["Open", "High", "Low", "Close"]
  atr:
    periods: [10, 14]
    sources: ["Close"]
  vwap:
    periods: [10]
    sources: ["Open", "High", "Low", "Close"]
  rvol:
    periods: [10, 20]
    sources: ["Volume"]
indexes:
  nifty50:
    [
      "ADANIENT",
      "ADANIPORTS",
      "APOLLOHOSP",
      "ASIANPAINT",
      "AXISBANK",
      "BAJAJ-AUTO",
      "BAJFINANCE",
      "BAJAJFINSV",
      "BEL",
      "BHARTIARTL",
      "CIPLA",
      "COALINDIA",
      "DRREDDY",
      "EICHERMOT",
      "ETERNAL",
      "GRASIM",
      "HCLTECH",
      "HDFCBANK",
      "HDFCLIFE",
      "HEROMOTOCO",
      "HINDALCO",
      "HINDUNILVR",
      "ICICIBANK",
      "ITC",
      "INDUSINDBK",
      "INFY",
      "JSWSTEEL",
      "JIOFIN",
      "KOTAKBANK",
      "LT",
      "M&M",
      "MARUTI",
      "NTPC",
      "NESTLEIND",
      "ONGC",
      "POWERGRID",
      "RELIANCE",
      "SBILIFE",
      "SHRIRAMFIN",
      "SBIN",
      "SUNPHARMA",
      "TCS",
      "TATACONSUM",
      "TATAMOTORS",
      "TATASTEEL",
      "TECHM",
      "TITAN",
      "TRENT",
      "ULTRACEMCO",
      "WIPRO",
    ]
